const APP_NAME = 'cryptick';
const DEFAULT_CHART_HEIGHT = 'h-32';
const DEFAULT_SELECTED_PRODUCT_IDS = ['BTC-USD', 'ETH-USD', 'SOL-USD'];

export { APP_NAME, DEFAULT_CHART_HEIGHT, DEFAULT_SELECTED_PRODUCT_IDS };
